[package]
authors = ["pjmp"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
description = "A npm inspired cargo subcommand for listing and updating binaries installed in $CARGO_HOME/bin."
edition = "2018"
homepage = "https://github.com/pjmp/cargo-updater"
keywords = ["cargo", "cargo-subcommand"]
license = "MIT OR Apache-2.0"
name = "cargo-updater"
readme = "README.md"
repository = "https://github.com/pjmp/cargo-updater"
version = "0.9.3"

[dependencies]
clap =  {version = "2.33.3", default-features = false, features = ["color", "suggestions"]}
colored = "2.0.0"
semver = "1.0.4"
term-table = "1.3.1"
anyhow = "1.0.43"
attohttpc = {version = "0.17.0", features = ["json"]}
serde_json = "1.0.67"

[profile.release]
opt-level = 3
lto = "fat"
panic = 'abort'
codegen-units = 1
