[package]
authors = ["pjmp"]
categories = ["command-line-interface", "command-line-utilities"]
description = "A npm inspired cargo subcommand for checking and updating installed binaries."
edition = "2018"
homepage = "https://github.com/pjmp/cargo-updater"
keywords = ["cargo", "cargo-subcommand"]
license-file = "LICENSE-MIT.md"
name = "cargo-updater"
readme = "README.md"
repository = "https://github.com/pjmp/cargo-updater"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
colored = "1.9.2"
futures = {version = "0.3", features = ["async-await"]}
miniserde = "0.1.12"
regex = "1.3.3"
reqwest = {version = "0.10", features = ["json"] }
semver = "0.9.0"
term-table = "1.2.0"
tokio = {version = "0.2", features = ["macros"] }

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
