[package]
authors = ["pjmp"]
categories = ["command-line-interface", "command-line-utilities"]
description = "A npm inspired cargo subcommand for checking and updating installed binaries."
edition = "2018"
homepage = "https://github.com/pjmp/cargo-updater"
keywords = ["cargo", "cargo-subcommand"]
license = "MIT"
name = "cargo-updater"
readme = "README.md"
repository = "https://github.com/pjmp/cargo-updater"
version = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap =  {version = "2.33.3", default-features = false, features = ["color", "suggestions"]}
colored = "1.9.2"
semver = "0.9.0"
term-table = "1.2.0"
anyhow = "1.0.31"
attohttpc = {version = "0.15.0", features = ["json"]}
serde = {version = "1.0.114", features = ["derive"]}

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
