name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: |
          cargo fmt
          git diff --quiet || (echo 'Unformatted, run `cargo fmt` before pushing.' && exit 1)
    - name: Lint
      run: cargo clippy --verbose -- -D warnings
    - name: Build
      run: cargo build --verbose
